In [71]:
#import the dependencies
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [72]:
#loading the data
data = pd.read_csv('Obesity.csv')
data.info()
data = data.drop(columns='ID',axis=1)
data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      108 non-null    int64
 1   Age     108 non-null    int64
 2   Gender  108 non-null    object
 3   Height  108 non-null    int64
 4   Weight  108 non-null    int64
 5   BMI     108 non-null    float64
 6   Label   108 non-null    object
dtypes: float64(1), int64(4), object(2)
memory usage: 6.0+ KB

     Age  Gender  Height  Weight   BMI          Label
0     25    Male     175      80  25.3  Normal Weight
1     30  Female     160      60  22.5  Normal Weight
2     35    Male     180      90  27.3     Overweight
3     40  Female     150      50  20.0    Underweight
4     45    Male     190     100  31.2          Obese
..   ...     ...     ...     ...   ...            ...
103   11    Male     175      10   3.9    Underweight
104   16  Female     160      10   3.9    Underweight
105   21    Male     180      15   5.6    Underweight
106   26  Female     150      15   5.6    Underweight
107   31    Male     190      20   8.3    Underweight

[108 rows x 6 columns]

In [73]:
data.head()

   Age  Gender  Height  Weight   BMI          Label
0   25    Male     175      80  25.3  Normal Weight
1   30  Female     160      60  22.5  Normal Weight
2   35    Male     180      90  27.3     Overweight
3   40  Female     150      50  20.0    Underweight
4   45    Male     190     100  31.2          Obese

In [74]:
data.isnull().sum()

Age       0
Gender    0
Height    0
Weight    0
BMI       0
Label     0
dtype: int64

In [75]:
contents = ['Gender', 'Label',]
lb = LabelEncoder()
for content in contents:
    data[content] = lb.fit_transform(data[content])

data

     Age  Gender  Height  Weight   BMI  Label
0     25       1     175      80  25.3      0
1     30       0     160      60  22.5      0
2     35       1     180      90  27.3      2
3     40       0     150      50  20.0      3
4     45       1     190     100  31.2      1
..   ...     ...     ...     ...   ...    ...
103   11       1     175      10   3.9      3
104   16       0     160      10   3.9      3
105   21       1     180      15   5.6      3
106   26       0     150      15   5.6      3
107   31       1     190      20   8.3      3

[108 rows x 6 columns]

In [76]:

#separating the target from features
x = data.drop(columns='Label', axis=1)
y = data['Label']

In [77]:
# #data standardization
# from sklearn.preprocessing import StandardScaler
# scaler=StandardScaler()
# standard_data=scaler.fit_transform(x)
# X=standard_data
# X

In [78]:
#splitting the data into train and test data
x_train,  x_test, y_train, y_test= train_test_split(x, y, test_size=0.15, stratify=y, random_state=3)

In [79]:
model =  LogisticRegression()
model.fit(x_train, y_train)

c:\Users\Masterkim\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [80]:
x_train_pred = model.predict(x_train)
training_accuracy =  accuracy_score(x_train_pred, y_train)
training_accuracy

x_test_pred = model.predict(x_test)
test_accuracy =  accuracy_score(x_test_pred, y_test)
print('The training accuracy: ', training_accuracy)
print('The test accuracy: ', test_accuracy)

The training accuracy:  0.8021978021978022
The test accuracy:  0.7058823529411765

In [81]:
#saving the trained model

import pickle
filename = 'trained_model.sav'
pickle.dump(model, open(filename, 'wb'))

In [82]:
#loading the saved model
loaded_model = pickle.load(open('trained_model.sav', 'rb'))

In [83]:
#making a predictive system
input_data = (25, 1, 175, 80,25.4)
input_array=np.asarray(input_data)
#reshape
input_array_reshape = input_array.reshape(1,-1)
prediction= loaded_model.predict(input_array_reshape)
print(prediction)

if (prediction == 0):
    print('The person is normal')
elif (prediction == 1):
    print('The person is Obese')
elif (prediction == 2):
    print('The person is Overweight')
else:
    print('The person is Underweight')




#1,25,Male,175,80,25.3,Normal Weight

[2]
The person is Overweight

c:\Users\Masterkim\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [84]:
x

     Age  Gender  Height  Weight   BMI
0     25       1     175      80  25.3
1     30       0     160      60  22.5
2     35       1     180      90  27.3
3     40       0     150      50  20.0
4     45       1     190     100  31.2
..   ...     ...     ...     ...   ...
103   11       1     175      10   3.9
104   16       0     160      10   3.9
105   21       1     180      15   5.6
106   26       0     150      15   5.6
107   31       1     190      20   8.3

[108 rows x 5 columns]